config/routes.rb
Rails.application.routes.draw do
  
  get 'static_page/splashscreen'
  
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'        
  end
  
  get 'groups/index', as: :user_root

  resources :users do
    resources :groups do
      resources :trades
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_page#splashscreen"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, author: user
    can :manage, Entity, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', dependent: :destroy
  has_many :trade_groups, dependent: :destroy
  has_many :trades, through: :trade_groups, dependent: :destroy
  has_one_attached :icon

  after_save :add_default_icon

  validates :name, presence: true

  def icon_thumbnail
    icon.variant(resize_to_limit: [100, 100]).processed
  end

  private

  def add_default_icon
    return if icon.attached?

    icon.attach(
      io: File.open(
        Rails.root.join(
          'app/assets/images/icon.png'
        )
      ), filename: 'icon.png',
      content_type: 'image/jpg'
    )
  end
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :trade_groups
  has_many :groups, through: :trade_groups

  validates :name, :amount, presence: true
  validates :amount, numericality: { only_integer: true }
end

app/models/trade_group.rb
class TradeGroup < ApplicationRecord
  belongs_to :trade, dependent: :destroy
  belongs_to :group, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are: :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trades, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id, dependent: :destroy
  has_one_attached :avatar

  validates :name, presence: true
  validates_associated :trades, :groups
  validates :name, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(author_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.where(author_id: current_user, id: params[:id])[0]
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      flash[:info] = 'Created succesfully'
      redirect_to user_groups_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    if current_user.groups.find(params[:id]).delete
      redirect_to user_groups_path(current_user), status: :see_other, notice: 'Group was successfully destroyed.'
    else
      flash[:error] = 'Unable to delete'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def splashscreen; end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def new
    @group = current_user.groups.find(params[:group_id])
    @trade = Trade.new
  end

  def index
    @group = current_user.groups.find(params[:group_id])
    @trades = @group.trades
  end

  def create
    @group = current_user.groups.find(params[:group_id])
    @trade = current_user.trades.create(trade_params)
    if @trade.save
      @trade_groups = @trade.trade_groups.create(group_id: @group.id, trade_id: @trade.id)
      if @trade_groups.save
        flash[:notice] = 'New transaction created successfully'
        redirect_to user_group_path(current_user, @group)
      else
        flash.now[:alert] = 'Trade group creation failed'
        render 'new', status: :unprocessable_entity
      end
    else
      flash.now[:alert] = 'Trade creation failed'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @group = current_user.groups.find(params[:group_id])
    @trade = current_user.trades.find(params[:id])
    @trade.destroy
    redirect_to user_group_path(current_user, @group), status: :see_other, notice: 'Trade was successfully destroyed.'
  end

  private

  def trade_params
    params.require(:trade).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: [ @current_user, Group.new], url: user_groups_url, method: :post) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
  
        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <% form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id, id: :group_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
  
    <div class="mx-6">
      <% form.label :name, required: true, style: "display: block" %>
      <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
    </div>
    <br />
    <br />
    <div class="mx-6">
      <% form.label :icon, required: true, style: "display: block" %>
      <%= form.file_field :icon, direct_upload: true, class:"form-control", placeholder:"Icon" %>
    </div>
    <br />
    <div class="mx-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <div class="my-6 border-solid border-1 bg-[#F5F5F5] p-4 mx-4 cursor-pointer">
    <div class="flex justify-between md:w-1/2">
    <% if group.icon.attached? %>
    <%= image_tag group.icon, class: "w-32 h-32 object-cover rounded-lg" %>
  <% else %>
    <img
      src="https://cdn.tailgrids.com/1.0/assets/images/cards/card-01/image-01.jpg"
      alt="image"
      class="w-32 h-32"
    />
  <% end %>
      <div class="flex flex-col justify-center">
        <h5 class="font-bold italic text-2xl"><%= group.name %><h5>
        <h5 class="font-bold text-sm">Total: $<%= group.trades.sum(:amount) %></h5>
      </div>
    </div>
  </div> 
</div>

app/views/groups/index.html.erb
<nav class="bg-[#3778C2] text-white p-2">
  <ul class="flex justify-between mr-6">
    <li class="text-4xl">
      <i class="fa fa-navicon"></i>
    </li>
    <li>
      <h2 class="font-bold text-3xl">Groups</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>

<div id="categories">
  <% if @groups.any? %>
    <% @groups.each do |group| %>
      <%= link_to user_group_path(current_user, group), class: "text-black no-underline" do %>
        <%= render group %>
      <% end %>
    <% end %>
  <% else %>
  <p class="text-base text-center font-bold">There are no groups. Please add a group</p>
  <% end %>
</div>
<div class="bg-[#5FB523] p-2 flex justify-center fixed-bottom">
  <%= link_to "New group", new_user_group_path(current_user), class: "btn btn-outline-dark w-75 p-2" %>
</div>

app/views/groups/new.html.erb
<nav class="bg-[#3778C2] text-white p-1">
  <ul class="flex justify-start gap-5 p-2">
    <li class="text-3xl mr-4">
      <%= link_to user_groups_path(current_user), class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-3xl">Add A Group</h2>
    </li>
  </ul>
</nav>

<div class="my-20">
  <%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<nav class="bg-[#3778C2] text-white p-1">
  <ul class="flex justify-between items-center mr-6 mt-2">
    <li class="text-3xl">
      <%= link_to user_groups_path(current_user), class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-xl pt-3">Group Details</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>

<%= render @group %>
<div class="mx-6">
  <%= button_to "Delete Group", user_group_path(current_user, @group), method: :delete, class: "btn btn-danger"%>
</div>


<h1 class="text-center font-bold text-xl mt-12">Trades</h1>
<div class="d-flex justify-content-end mr-6 my-3">
  <%= link_to "New Transaction", new_user_group_trade_path(current_user, @group), class: "btn btn-primary" %>
</div>

<% if @group.trades.any? %>
  <div class="mx-4 md:mx-48 border-solid border-1 bg-[#F5F5F5] p-4">
    <% @group.trades.order(created_at:'DESC').each do |trade| %>
      <div class="flex justify-between border-solid border-1 bg-white py-3 px-4 mb-3">
        <div class="flex flex-col justify-center pt-1">
          <p class="font-bold italic"><%= trade.name %></p>
          <p class="font-bold italic"><%= trade.created_at.strftime("%d-%b-%Y")%></p></p>
        </div>
        <div class="flex flex-col">
          <p class="font-bold">$<%= trade.amount %></p>
          <%=button_to "Delete", user_group_trade_path(current_user, @group, trade), method: :delete, class:"btn btn-primary px-2"%>
        </div>
      </div>
    <% end %>
  <div>
<% else %>
  <p class="font bold italic text-center text-base mx-6">There are no trades to show. Please Add a new transaction</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    </body>
</html>

app/views/static_page/splashscreen.html.erb
<div class="flex flex-col gap-4 justify-center items-center my-36 font-bold">
  <div class="mx-6 flex flex-col gap-2">
    <%= image_tag "budget.png" %>
    <h5 class="text-[#9D47FF] text-center italic">Budget App</h5>
  </div>

  <div class="border-solid border-1 bg-[#3778C2] w-11/12 text-center p-2">
    <%= link_to "Log in", new_user_session_path, class: "text-decoration-none text-white" %>
  </div>
  <div class="border-solid border-1 bg-[#3778C2] w-11/12 text-center p-2">
    <%= link_to "Sign Up", new_user_registration_path, class: "text-decoration-none text-white"%>
  </div>
</div>

app/views/trades/_form.html.erb
<%= form_with(model: [ User.new, Group.new, Trade.new], url: user_group_trades_path, method: :post) do |form| %>
    <% if trade.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>
  
        <ul>
          <% trade.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <% form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id, id: :trade_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
  
    <div class="mx-6">
      <% form.label :name, style: "display: block" %>
      <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
    </div>
    <br />
    <div class="mx-6">
      <% form.label :amount, style: "display: block" %>
      <%= form.text_field :amount, class:"form-control", placeholder:"Amount" %>
    </div>
    <br />
    <div class="mx-6">
      <% form.label :group, style: "display: block" %>
      <%= form.text_field :group, value:@group.name, class:"form-control" %>
    </div>
    <br />
    <div class="mx-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  
  

app/views/trades/new.html.erb
<nav class="bg-[#3778C2] text-white py-2">
  <ul class="flex justify-between mr-4">
    <li class="text-3xl">
      <%= link_to user_groups_path(current_user), class: "text-white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </li>
    <li>
      <h2 class="font-bold text-2xl">New Transaction</h2>
    </li>
    <li class="font-bold text-4xl">
      <%= button_to destroy_user_session_path, method: :delete do %>   
        <i class="fa fa-sign-out"></i>
      <% end %>
    </li>
  </ul>
</nav>

<div class="py-20">
  <%= render "form", trade: @trade %>
</div>

<br>